#!/bin/bash
#postrm script for Booktype

set -e

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

VIRTUAL_ENV_DIR="/var/lib/booktype/"

case "$1" in
  purge|remove)
  ;;

  echo -e "\n*** Removing virtualenv from ${VIRTUAL_ENV_DIR} ***"

  rm -r ${VIRTUAL_ENV_DIR}

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
      echo "postrm called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

#DEBHELPER#

exit 0
